// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService provides application management functionality
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetApps returns all available applications
 * @returns {$CancellablePromise<$models.AppInfo[]>}
 */
export function GetApps() {
    return $Call.ByID(1862096634).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetFavorites returns all favorited applications
 * @returns {$CancellablePromise<$models.AppInfo[]>}
 */
export function GetFavorites() {
    return $Call.ByID(1863012763).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * LaunchApp launches an application by its exec path
 * @param {string} execPath
 * @returns {$CancellablePromise<void>}
 */
export function LaunchApp(execPath) {
    return $Call.ByID(1748461220, execPath);
}

/**
 * SearchApps searches for applications based on the query
 * @param {string} query
 * @returns {$CancellablePromise<$models.AppInfo[]>}
 */
export function SearchApps(query) {
    return $Call.ByID(113501558, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ToggleFavorite toggles the favorite status of an application
 * @param {string} appName
 * @returns {$CancellablePromise<void>}
 */
export function ToggleFavorite(appName) {
    return $Call.ByID(1461788062, appName);
}

// Private type creation functions
const $$createType0 = $models.AppInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
