// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppsByCategory(arg1:string):Promise<Array<Record<string, any>>>;

export function GetCategories():Promise<Array<string>>;

export function GetFavorites():Promise<Array<Record<string, any>>>;

export function GetRecentlyUsed(arg1:number):Promise<Array<Record<string, any>>>;

export function LaunchApp(arg1:string):Promise<void>;

export function RefreshApps():Promise<void>;

export function SearchApps(arg1:string):Promise<Array<Record<string, any>>>;

export function ToggleFavorite(arg1:string):Promise<void>;
