// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppsByCategory(arg1) {
  return window['go']['main']['App']['GetAppsByCategory'](arg1);
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function GetFavorites() {
  return window['go']['main']['App']['GetFavorites']();
}

export function GetRecentlyUsed(arg1) {
  return window['go']['main']['App']['GetRecentlyUsed'](arg1);
}

export function LaunchApp(arg1) {
  return window['go']['main']['App']['LaunchApp'](arg1);
}

export function RefreshApps() {
  return window['go']['main']['App']['RefreshApps']();
}

export function SearchApps(arg1) {
  return window['go']['main']['App']['SearchApps'](arg1);
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}
